export const DUMMY_USERS = [
  {
    uid: "faculty01",
    name: "Madhumita Chanda",
    email: "priya.sharma@jntugv.edu",
    role: "faculty",
    qualification: "M.Tech",
    department: "IT",
    assignedHod: "hod01",
    password: "faculty123",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2020-06-10",
    place: "Vizianagaram",
    rating: "4.2 / 5",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000001",
    emailLink: "mailto:priya.sharma@jntugv.edu",
  },
  {
    uid: "faculty02",
    name: "Bobbadi Manasa",
    email: "rajesh.kumar@jntugv.edu",
    role: "faculty",
    qualification: "M.Tech",
    department: "IT",
    assignedHod: "hod02",
    password: "faculty456",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2021-01-15",
    place: "Hyderabad",
    rating: "4.0 / 5",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000002",
    emailLink: "mailto:rajesh.kumar@jntugv.edu",
  },
  {
    uid: "hod02",
    name: "Dr. Ch. Bindu Madhuri",
    email: "bindumadhuri@jntugv.edu",
    role: "hod",
    qualification: "Ph.D",
    department: "IT",
    password: "hod123",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2015-08-20",
    place: "Vizianagaram",
    rating: "4.5 / 5",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000003",
    emailLink: "mailto:bindumadhuri@jntugv.edu",
  },
  {
    uid: "principal01",
    name: "Prof. R. Rajeswara Rao",
    email: "principal@jntugv.edu",
    role: "principal",
    qualification: "Ph.D",
    department: "Administration",
    password: "principal123",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2010-03-12",
    place: "Vizianagaram",
    rating: "4.7 / 5",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000004",
    emailLink: "mailto:principal@jntugv.edu",
  },
  {
    uid: "registrar01",
    name: "Prof. Dr. G. Jaya Suma",
    email: "registrar@jntugv.edu",
    role: "registrar",
    qualification: "Ph.D",
    department: "Administration",
    password: "registrar123",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2012-09-05",
    place: "Vizianagaram",
    rating: "4.6 / 5",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000005",
    emailLink: "mailto:registrar@jntugv.edu",
  },
  {
    uid: "systemadmin",
    name: "System Admin",
    email: "systemadmin@jntugv.edu",
    role: "registrar",
    qualification: "N/A",
    department: "Administration",
    password: "admin123",
    profilePic: "https://cdn-icons-png.flaticon.com/512/8608/8608769.png",
    dateOfJoining: "2022-01-01",
    place: "Hyderabad",
    rating: "N/A",
    linkedin: "https://linkedin.com/in/placeholder",
    whatsapp: "https://wa.me/910000000006",
    emailLink: "mailto:systemadmin@jntugv.edu",
  },
];

export const DUMMY_REQUESTS = [
  {
    id: "req001",
    requesterId: "faculty01",
    requesterName: "Madhumita Chanda",
    requesterDepartment: "IT",
    requestType: "Casual Leave",
    startDate: "2025-09-10",
    endDate: "2025-09-11",
    reason: "Family function in hometown.",
    status: "approved",
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2025-09-04T11:00:00Z",
    attachments: [],
    historyLog: [
      {
        action: "Submitted by Faculty",
        user: "Madhumita Chanda",
        timestamp: "2025-09-01T10:00:00Z",
      },
      {
        action: "Approved by HOD",
        user: "Dr.Ch.Bindu Madhuri",
        timestamp: "2025-09-02T14:30:00Z",
      },
      {
        action: "Approved by Principal",
        user: "Prof. R. Rajeswara Rao",
        timestamp: "2025-09-03T09:00:00Z",
      },
      {
        action: "Final Approval by Registrar",
        user: "Prof.Dr.G.Jaya Suma",
        timestamp: "2025-09-04T11:00:00Z",
      },
    ],
  },
  {
    id: "req002",
    requesterId: "faculty02",
    requesterName: "Bobbadi Manasa",
    requesterDepartment: "IT",
    requestType: "Medical Leave",
    startDate: "2025-09-15",
    endDate: "2025-09-18",
    reason: "Scheduled minor surgery, medical documents attached.",
    status: "pending_principal",
    createdAt: "2025-09-03T11:00:00Z",
    updatedAt: "2025-09-04T10:00:00Z",
    attachments: [],
    historyLog: [
      {
        action: "Submitted by Faculty",
        user: "Bobbadi Manasa",
        timestamp: "2025-09-03T11:00:00Z",
      },
      {
        action: "Approved by HOD",
        user: "Dr.Ch.Bindu Madhuri",
        timestamp: "2025-09-04T10:00:00Z",
      },
    ],
  },
  {
    id: "req003",
    requesterId: "faculty01",
    requesterName: "Madhumita Chanda",
    requesterDepartment: "IT",
    requestType: "On-Duty",
    startDate: "2025-10-05",
    endDate: "2025-10-07",
    reason: "Attending an international conference on AI.",
    status: "pending_hod",
    createdAt: "2025-09-04T09:30:00Z",
    updatedAt: "2025-09-04T09:30:00Z",
    attachments: [],
    historyLog: [
      {
        action: "Submitted by Faculty",
        user: "Madhumita Chanda",
        timestamp: "2025-09-04T09:30:00Z",
      },
    ],
  },
  {
    id: "req004",
    requesterId: "faculty02",
    requesterName: "Bobbadi Manasa",
    requesterDepartment: "IT",
    requestType: "Casual Leave",
    startDate: "2025-09-20",
    endDate: "2025-09-20",
    reason: "Personal work.",
    status: "rejected_hod",
    createdAt: "2025-09-02T16:00:00Z",
    updatedAt: "2025-09-03T17:00:00Z",
    attachments: [],
    historyLog: [
      {
        action: "Submitted by Faculty",
        user: "Bobbadi Manasa",
        timestamp: "2025-09-02T16:00:00Z",
      },
      {
        action: "Rejected by HOD",
        user: "Dr.Ch.Bindu Madhuri",
        timestamp: "2025-09-03T17:00:00Z",
        comment:
          "Insufficient reason provided and high workload in the department.",
      },
    ],
  },
  {
    id: "req005",
    requesterId: "faculty01",
    requesterName: "Madhumita Chanda",
    requesterDepartment: "IT",
    requestType: "Medical Leave",
    startDate: "2025-09-22",
    endDate: "2025-09-25",
    reason: "Viral fever. Doctor advised rest.",
    status: "pending_registrar",
    createdAt: "2025-09-04T13:00:00Z",
    updatedAt: "2025-09-04T15:00:00Z",
    attachments: [],
    historyLog: [
      {
        action: "Submitted by Faculty",
        user: "Madhumita Chanda",
        timestamp: "2025-09-04T13:00:00Z",
      },
      {
        action: "Approved by HOD",
        user: "Dr.Ch.Bindu Madhuri",
        timestamp: "2025-09-04T14:00:00Z",
      },
      {
        action: "Approved by Principal",
        user: "Prof. R. Rajeswara Rao",
        timestamp: "2025-09-04T15:00:00Z",
      },
    ],
  },
];
